title: othmane01 blog
email: its.othmne01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of CTF writeups, cybersecurity notes, and penetration testing walkthroughs documenting web exploitation techniques and lessons learned from real security challenges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://othmane01.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /writeups/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /writeups/:title/
github_username:  othmane01-bin

# Build settings
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

